AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: infrastructurez for the twitter bot

Parameters:
  TwitterConsumerKey:
    Type: String
  TwitterConsumerSecret:
    Type: String
  TwitterAccessToken:
    Type: String
  TwitterAccessTokenSecret:
    Type: String
  LambdaFunctionName:
    Type: String
    Default: gitwishes-function
  DynamoDBTableName:
    Type: String
    Default: gitwishes-messages

Resources:

  GitWishesLambdaBot:
    Type: AWS::Serverless::Function
    DependsOn:
      - GitWishesRole
      - GitWishesDB
    Properties:
      Handler: function.handler
      Runtime: python3.6
      Role: !GetAtt [GitWishesRole, Arn]
      CodeUri: ./dist
      FunctionName: !Ref LambdaFunctionName
      Environment:
        Variables:
          TWITTER_CONSUMER_KEY: !Ref TwitterConsumerKey
          TWITTER_CONSUMER_SECRET: !Ref TwitterConsumerSecret
          TWITTER_ACCESS_TOKEN: !Ref TwitterAccessToken
          TWITTER_ACCESS_TOKEN_SECRET: !Ref TwitterAccessTokenSecret
          DB_TABLE_NAME: !Ref DynamoDBTableName

  GitWishesRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: gitwishes-service-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action: sts:AssumeRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  GitWishesDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoDBTableName
      KeySchema:
        - AttributeName: MessageBody
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: MessageBody
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true

  CommitSearchEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      ScheduleExpression: "cron(0 1 * * ? *)"
      Name: CommitSearchEvent
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt GitWishesLambdaBot.Arn
          Id: "CommitSearchEventScheduler"

  TweetEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      ScheduleExpression: "rate(4 hours)"
      Name: TweetEvent
      State: "ENABLED"
      Targets:
        -
          Arn: !GetAtt GitWishesLambdaBot.Arn
          Id: "TweetEventScheduler"

  CommitSearchEventLambdaPermissions:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt [CommitSearchEventRule, Arn]

  TweetEventLambdaPermissions:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: !GetAtt [TweetEventRule, Arn]

